# Generated by Django 5.0.3 on 2024-04-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_customer_balance_customer_cardid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
